#!/usr/bin/env python
import re, sys

if len(sys.argv) < 2:
    fn = "PKGBUILD"
else:
    fn = sys.argv[1]

pkgrel = "1"
epoch = "0"
with open(fn) as f:
    for line in f:
        m = re.match("pkgver=(.*)", line)
        if m:
            pkgver, = m.groups()
            continue
        m = re.match("pkgrel=(.*)", line)
        if m:
            pkgrel, = m.groups()
            continue
        m = re.match("epoch=(.*)", line)
        if m:
            epoch, = m.groups()
            continue

pkgver = pkgver.strip()
pkgrel = pkgrel.strip()
epoch = int(epoch)

if epoch == 0:
    epoch = ""
else:
    epoch = "{}:".format(epoch)

if pkgrel == "1":
    pkgrel = ""
else:
    pkgrel = "-{}".format(pkgrel)

sys.stdout.write(epoch + pkgver + pkgrel + "\n")
sys.stdout.flush()
