name: build
on:
  pull_request:
  push:
  schedule:
    - cron: 35 8 3 * *
  workflow_dispatch:
jobs:
  intro:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate_matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: generate_matrix
        run: |
          jq -Rnr '"::set-output name=matrix::" + ({"include": [{"pkg": inputs}]} | tostring)' packages.conf
  build:
    needs: intro
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.intro.outputs.matrix) }}
    runs-on: ubuntu-latest
    env:
      PKGDIR: pkg
    steps:
      - run: git clone https://aur.archlinux.org/${{ matrix.pkg }}.git pkg
        # steps named "test_*" are used by ./buildpkg for staging tests
      - name: test_prepare
        # workaround for https://bugs.archlinux.org/task/65042
        run: |
          if grep '^pkgname = \(ghc-pristine|stack-bin\)$' "${PKGDIR}/.SRCINFO"; then
              echo NAMCAP_DISABLE=true >> $GITHUB_ENV
          fi
      - name: test_run
        uses: Rufflewind/pkgbuild-action@master
        with:
          pkgdir: ${{ env.PKGDIR }}
          aurDeps: true
          namcapDisable: $${ env.NAMCAP_DISABLE }}
