name: build
on:
  pull_request:
  push:
  schedule:
    - cron: 35 8 3 * *
  workflow_dispatch:
jobs:
  intro:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: generate-matrix
        run: |
          jq -Rnr '"::set-output name=matrix::" + ({"include": [{"pkg": inputs}]} | tostring)' packages.conf
  build:
    needs: intro
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.intro.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git clone https://aur.archlinux.org/${{ matrix.pkg }}.git build
      - uses: ./.github/actions/test
        with:
          build-dir: build
          out-dir: out
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.pkg }}
          path: out/mainpkgs
